


The following chapter introduces articles that correspond with the subject of the current thesis and are considered as fundamentals of modern finance.
Specifically, the beginning contains financial market models. The next subchapter includes basic investment effectiveness indicators that implicitly or explicitly result from the fundamental formulas from the first subchapter.

## Selected financial market models and theory


Works considered as a fundament of quantitative finance and investments are Sharpe \cite{Sharpe1964}, Lintner \cite{Lintner1965}, and Mossin \cite{Mossin1966}. All these authors, almost simultaneously, formulated Capital Asset Pricing Model (CAPM) that describes dependability between rate of return and its risk, risk of the market portfolio, and risk premium.
Assumptions in the model are as follows:

* Decisions in the model regard only one period,
* Market participants has risk aversion, i.e. their utility function is related with plus sign to rate of return, and negatively to variance of portfolio rate of return,
* Risk-free rate exists,
* Asymmetry of information non-existent,
* Lack of speculative transactions,
* Lack of transactional costs, taxes included,
* Market participants can buy a fraction of the asset,
* Both sides are price takers,
* Short selling exists,

Described by the following model formula is as follows:
$$
E(R_P)=R_F+\frac{\sigma_P}{\sigma_M}\times[E(R_M)-R_F]
$$
where:

* $E(R_P )$ -- the expected portfolio rate of return,
* $E(R_M)$ -- the expected market rate of return,
* $R_F$ -- risk-free rate,
* $\sigma_P$ -- the standard deviation of the rate of return on the portfolio,
* $\sigma_M$ -- the standard deviation of the rate of return on the market portfolio.

$E(R_P)$ function is also known as Capital Market Line (CML). Any portfolio lies on that line is effective, i.e. its rate of return corresponds to embedded risk.
The next formula includes all portfolios, single assets included. It is also known as Security Market Line (SML) and is given by the following equation:
$$ \label{eq:erl}
E(R_i)=R_F+\beta_i\times[E(R_M)-R_F]
$$
where:

* $E(R_i)$ -- the expected $i$-th portfolio rate of return,
* $E(R_M)$ -- the expected market rate of return,
* $R_F$ -- risk-free rate,
* $\beta_i$ -- Beta factor of the $i$-th portfolio.


## The Modern Portfolio Theory
The following section discuss the Modern Portfolio Theory developed by Henry Markowitz \cite{Markowitz1952}. The author introduced the model in which the goal
(investment criteria) is 
not only to maximize the return but also to minimize the variance. He claimed that by combining assets in different composition it is possible to obtain the 
portfolios with the same return but different levels of risk. The risk reduction is possible by diversification, i.e. giving proper weights for each asset 
in the portfolio. Variance of portfolio value can be effectively reduced by analyzing mutual relations between returns on assets with use of methods in statistics
(correlation and covariance matrices). It is important to say that any additional asset in portfolio reduces minimal variance for a given portfolio 
but it is the correlation what really impacts the magnitude.
The Markowitz theory implies that for any assumed expected return there is the only one portfolio that minimizes risk. Alternatively, there is only one portfolio 
that maximizes return for the assumed risk level. The important term, which is brought in literature, is the effective portfolio, i.e. the one that meets conditions
above.
The combination of optimal portfolios on the bullet.

Bullet figure

The Markowitz concept is determined by the assumption that investors are risk-averse. This observation is described by the following formula:

$$
E(U)<U(E(X))
$$
where:

* $E(U)$ -- the expected value of utility from payoff;
* $U(E(X))$ -- utility of the expected value of payoff.

The expected value of payoff is given by the following formula:
$$
E(U)=\sum_{i=1}^{n}\pi_iU(c_i)
$$
where:

* $\pi_i$ -- probability of the $c_i$ payoff,
* $U(c_i)$ -- utility from the $c_i$ payoff.

One of the MPT biggest flaws is the fact that it is used for ex post analysis. Correlation between assets changes overtime so results must be recalculated. Real portfolio risk may be underestimated. Also, time window can influence the results.

## The efficient market hypothesis

In 1965, Eugene Fama introduced the efficient market term \cite{Fama1965}. Fama claimed that an efficient market is the one that instanteneously discounts the new information arrival in market price of a given asset. Because this definition applies to financial markets, it had determined the further belief that it is not possible to beat the market because assets are perfectly priced. Also, if this hypothesis would be true, market participants cannot be better or worse. Their portfolio return would be a function of new, unpredictable information. In that respect, the only role of an investor is to manage his assets so that the risk is acceptable. 


