<!--!Rnw root = ../../masters_thesis.Rnw -->

<!--\SweaveOpts{concordance=TRUE} -->


## Selected investment performance measures

Introduced articles does not include any indicator that would explicitly measure portfolio management effectiveness. 
Equations that result from the authors' work are important because some of further developed measures are CAPM-based. 
The most known are the Sharpe ratio, the Treynor ratio, and the Jensen's alpha. Popularity of these indicator comes from the fact that 
they are easy to understand for the average investor. \cite{Marte2012}
In \cite{Sharpe1966}, the author introduced the $\frac{R}{V}$ indicator, also known as the Sharpe Ratio ($S$), which is given by the following formula:
$$
S_i=\frac{E(R_i-R_F)}{\sigma_i}
$$
where: 

* $R_i$ -- the $i$-th portfolio rate of return,
* $R_F$ -- risk-free rate
$\sigma_i$ -- the standard deviation of the rate of return on the $i$-th portfolio.

Treynor (Treynor1965) proposed other approach in which denominator includes $\beta_i$ instead of $\sigma_i$. The discussed formula is given by:
$$
T_i=\frac{R_i-R_F}{\beta_i}
$$
where:

* $R_i$ -- the $i$-th portfolio rate of return,
* $R_F$ -- Risk-free rate
* $\beta_i$ -- Beta factor of the $i$-th portfolio.

Both indicators, i.e. $S$ and $T$ are relative measures. Their value should be compared with a benchmark to determine if a given portfolio is well-managed. If they are
higher (lower), it means that analyzed portfolios were better (worse) than a benchmark.
The last measure, very popular among market participants, is the Jensen's alpha. It is given as follows:
$$
$$
where:

* $R_i$ -- the $i$-th portfolio rate of return,
* $R_F$ -- Risk-free rate
* $\beta_i$ -- Beta factor of the $i$-th portfolio.

The Jensen's alpha is an absolute measure and is calculated as the difference between actual and CAPM model-implied rate of return. The greater the value is,
the better for the $i$-th observation.

The differential Sharpe ratio - this measure is a dynamic extension of Sharpe ratio. By using the indicator, it can be possible to capture a marginal impact of return at time t on the Sharpe Ratio. The procedure of computing it starts with the following two formulas:
$$
A_n=\frac{1}{n}R_n+\frac{n-1}{n}A_{n-1}
$$
$$
B_n=\frac{1}{n}R_n^2+\frac{n-1}{n}B_{n-1}
$$
At $t=0$ both values equal to 0. They serve as the base for calculating the actual measure - an exponentially moving Sharpe ratio on $\eta$ time scale.
$$
S_t=\frac{A_t}{K_\eta\sqrt{B_t-A_t^2}}
$$
where:

* $A_t=\eta R_t+(1-\eta)A_{t_1}$ 
* $B_t=\eta R_t^2+(1-\eta)B_{t_1}$ 
* $K_\eta=(\frac{1-\frac{\eta}{2}}{1-\eta})$


Using of the differential Sharpe ratio in algorithmic systems is highly desirable due to the following facts \cite{Moody1997}:

* Recursive updating - it is not needed to recompute the mean and standard deviation of returns every time the measure value is evaluated. 
Formula for $A_t$ ($B_t$) enables to very straightforward calculation of the exponential moving Sharpe ratio, just by updating for  $R_t$ ($R_t^2$)
* Efficient on-line optimization - the way the formula is provided directs to very fast computation of the whole statistic with just updating the most recent values
* Interpretability - the differential Sharpe ratio can be easily explained, i.e. it measures how the most recent return affect the Sharpe ratio (risk and reward).



The drawdown is the measure of the decline from a historical peak in an asset.
The formula is given as follows:

$$
D(T)=\max\{max_{0, t\in (0,T)} X(t)-X(\tau)\}
$$


The Sterling ratio (SR)


The maximum drawdown (MDD) at time $T$ is the maximum of the Drawdown over the asset history. The formula is given as follows:

$$
MDD(T)=\max_{\tau\in (0,T)}[\max_{t\in (0,\tau)} X(t)-X(\tau)]
$$

