require(rpm2)
require(assertthat)
require(magrittr)
require(stringr)
require(plyr)
debugonce(rpm2:::.swap)

convertDocs(path_folder = './data/Rmd', new_path_folder = './data/Rnw3', recursive = T)
debugonce(rpm2:::.swapItems)
convertDocs(type = 'Rmd', path_folder = './data/Rmd/chapters/subchapters', new_path_folder = './data/Rnw3', recursive = T)
